spring:
  application:
    name: drawit

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/drawit
    username: postgres
    password: VGpostgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



